### ISSUE TITLE
convert ERROR

### ISSUE THREAD

**Issue by cucibala** [LoSealL/openvino2onnx#19]
![image](https://github.com/user-attachments/assets/ba4c2a2a-4764-4b18-885b-0f6c1c760138)

**Comment by cucibala** [comment]
![image](https://github.com/user-attachments/assets/5a88b7e8-a127-4581-9720-015a86a5f660)

**Comment by cucibala** [comment]
> ![image](https://private-user-images.githubusercontent.com/48320342/387523772-5a88b7e8-a127-4581-9720-015a86a5f660.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE5OTc2NjAsIm5iZiI6MTczMTk5NzM2MCwicGF0aCI6Ii80ODMyMDM0Mi8zODc1MjM3NzItNWE4OGI3ZTgtYTEyNy00NTgxLTk3MjAtMDE1YTg2YTVmNjYwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE5VDA2MjI0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJiNzYzMWNhNTgyZGNhM2RlMWNlY2I2MTkzMzgyNmM1ZjQ2NTE4ZTQ0OGRhNzQ5NzNjZWUyNWQ5MzA2M2M4YWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.y3cuWmI-NsOvwpzFHRofL9FBdlFtjpKhbUz_-EA3AHI)

 v1.0 Error

**Comment by LoSealL** [comment]
Can you try PR #23 ?

**Comment by cucibala** [comment]
Now it's OK, but I'm having trouble switching to another model

**Comment by cucibala** [comment]
![1732076797488](https://github.com/user-attachments/assets/d84a513f-310d-474d-9799-ac201ab440d5)
![image](https://github.com/user-attachments/assets/72925b07-db64-4284-baff-db5a27f9dd20)

**Comment by LoSealL** [comment]
can you share the xml or this model? (bin is not required), or you can share a small snippet around this operator: `NormalizeL2_22659`

**Comment by cucibala** [comment]
I sent an email to your mailbox

**Comment by LoSealL** [comment]
gotcha

**Comment by cucibala** [comment]
When I load a model using OpenCV, I get the following error

**Comment by cucibala** [comment]
it's ok, but use error

**Comment by LoSealL** [comment]
what about onnxruntime? can you check `onnxruntime_test model.onnx 1`

**Comment by cucibala** [comment]
> onnxruntime_test model.onnx 1

![image](https://github.com/user-attachments/assets/67160c97-10ff-4b71-806b-2d582a494219)

**Comment by cucibala** [comment]
> what about onnxruntime? can you check `onnxruntime_test model.onnx 1`

![image](https://github.com/user-attachments/assets/4c2dcf5a-78a9-4a7f-b52d-623f200188b1)

**Comment by LoSealL** [comment]
For a quick validation on OnnxRuntime, can you modify your xml as follows?:

From
```
<layer id="707" name="Result_22666" type="Result" version="opset1">
			<input>
				<port id="0">
					<dim>1</dim>
					<dim>128</dim>
				</port>
			</input>
</layer>
```

To
```
<layer id="707" name="Result_22666" type="Result" version="opset1">
			<input>
				<port id="0" precision="FP32">
					<dim>1</dim>
					<dim>128</dim>
				</port>
			</input>
</layer>
```

**Comment by LoSealL** [comment]
> When I load a model using OpenCV, I get the following error
> 
> OpenCV(4.5.4) F:\repos\opencv-4.5.4\modules\dnn\src\onnx\onnx_importer.cpp:739: error: (-2:Unspecified error) in function 'cv::dnn::dnn4_v20211004::ONNXImporter::handleNode'
> 
> > Node [Conv]:(Convolution_21635_output2) parse error: OpenCV(4.5.4) F:\repos\opencv-4.5.4\modules\dnn\src\layers\layers_common.cpp:106: error: (-5:Bad argument) kernel_size (or kernel_h and kernel_w) not specified in function 'cv::dnn::util::getKernelSize'

For OpenCV, it seems it needs `kernel_shape` attribute while it is not a mandatory attribute as onnx describes [here](https://onnx.ai/onnx/operators/onnx__Conv.html).

> kernel_shape - INTS :
> The shape of the convolution kernel. If not present, should be inferred from input W.

**Comment by cucibala** [comment]
> For a quick validation on OnnxRuntime, can you modify your xml as follows?:
> 
> From
> 
> ```
> <layer id="707" name="Result_22666" type="Result" version="opset1">
> 			<input>
> 				<port id="0">
> 					<dim>1</dim>
> 					<dim>128</dim>
> 				</port>
> 			</input>
> </layer>
> ```
> 
> To
> 
> ```
> <layer id="707" name="Result_22666" type="Result" version="opset1">
> 			<input>
> 				<port id="0" precision="FP32">
> 					<dim>1</dim>
> 					<dim>128</dim>
> 				</port>
> 			</input>
> </layer>
> ```

![image](https://github.com/user-attachments/assets/1cbe65f8-f20a-4204-b113-6ab428fffa40)
cause another error

**Comment by LoSealL** [comment]
root caused, will fix this issue

**Comment by cucibala** [comment]
> > When I load a model using OpenCV, I get the following error
> > OpenCV(4.5.4) F:\repos\opencv-4.5.4\modules\dnn\src\onnx\onnx_importer.cpp:739: error: (-2:Unspecified error) in function 'cv::dnn::dnn4_v20211004::ONNXImporter::handleNode'
> > > Node [Conv]:(Convolution_21635_output2) parse error: OpenCV(4.5.4) F:\repos\opencv-4.5.4\modules\dnn\src\layers\layers_common.cpp:106: error: (-5:Bad argument) kernel_size (or kernel_h and kernel_w) not specified in function 'cv::dnn::util::getKernelSize'
> 
> For OpenCV, it seems it needs `kernel_shape` attribute while it is not a mandatory attribute as onnx describes [here](https://onnx.ai/onnx/operators/onnx__Conv.html).
> 
> > kernel_shape - INTS :
> > The shape of the convolution kernel. If not present, should be inferred from input W.

![image](https://github.com/user-attachments/assets/213c0a42-4e3c-4155-bf05-e486855beb0a)
I converted the model, but I still get the same error

**Comment by LoSealL** [comment]
#28 solved 2 issues:
- add kernel_shape to conv (opencv error)
- cast pads to int64 (Pad_21633 error)

For `invalid data type 0`, keep the change of xml, it suppose to deduce the correct data type automatically
