### ISSUE TITLE
During the conversion from openvino to onnx the kernel sizes are being as zeros for the convolution layers

### ISSUE THREAD

**Issue by HemaSowjanyaMamidi** [LoSealL/openvino2onnx#20]
I converted the model from openvino format i.e, xml and bin to ONNX. But during the conversion there is some loss of information in the convoulutional layers. The kernel sizes are coming as zeros.

[models.zip](https://github.com/user-attachments/files/17660688/models.zip)

Please find the attachment for the models

**Comment by LoSealL** [comment]
Please try v1.0.1 again, solved by #22
