### ISSUE TITLE
LayerNormalization Scale is 1 ?

### ISSUE THREAD

**Issue by cucibala** [LoSealL/openvino2onnx#29]
I don't know if it's a bug or something, the converted LayerNormalization Scale is 1
When I want to convert this onnx to ncnn, an error occurs. I check the model structure and the LayerNormalization input size is 2, but the value inside crashes directly.

**Comment by cucibala** [comment]
![image](https://github.com/user-attachments/assets/db9ff805-c574-445d-8299-c438bca35733)
![image](https://github.com/user-attachments/assets/b26777ad-ca98-4d10-8166-a8e9c219772b)

**Comment by cucibala** [comment]
![image](https://github.com/user-attachments/assets/f593ea4e-0e0d-4459-921a-11337a6efaa1)

**Comment by cucibala** [comment]
![image](https://github.com/user-attachments/assets/49ffb308-d815-48ca-a1f9-f2895b5122c7)
I had to comment out what was there for it to convert, I don't know if this is normal

**Comment by LoSealL** [comment]
What's the original `MVN_21619` looks like?
