### ISSUE TITLE
Error merging shape info for output

### ISSUE THREAD

**Issue by tianyu06030020** [LoSealL/openvino2onnx#32]
hi , I get follow errors when used converted openvino xml:

![image](https://github.com/user-attachments/assets/206a2ffa-f9d2-4ce8-8443-943425094062)

the xml file is:
[selfie_multiclass_256x256.zip](https://github.com/user-attachments/files/18090189/selfie_multiclass_256x256.zip)

thx!

**Comment by LoSealL** [comment]
Not reproduced from your attached file.

BTW, I could not recognize `Gather_out0` from your XML, is that a node or data name?

**Comment by LoSealL** [comment]
Oh, I found where those warnings come out!

There is a bug of `onnxruntime` when processing some operators of onnx opset 19, you can use

```
openvino2onnx selfie_multiclass_256x256.xml -v 17
```

To downgrade onnx opset to 17. I've written complete rules to support onnx downgradation.

**Comment by tianyu06030020** [comment]
> ```
> openvino2onnx selfie_multiclass_256x256.xml -v 17
> ```
I tried, succeed!, Thx
